CC=g++ -std=gnu++11
FILES=main.cpp lambda.cpp func_obj.cpp bind.cpp map.cpp fold.cpp trans.cpp smart_pointer.cpp functor.cpp tuples.cpp monad.cpp
OUT_EXE=main
build: $(FILES)
	$(CC) -o $(OUT_EXE) $(FILES)
clean:
	rm -f *.o core


